import './globals.css'
import { Inter } from 'next/font/google'
import Header from "@/app/Components/Header/Header";
import Footer from "@/app/Components/Footer/Footer";
import {useStore} from "@/src/store";
import StoreInitializer from "@/app/StoreInitialier/storeInitializer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

  export default async function RootLayout({ children }) {

  const dataRes = await fetch("http://localhost:8080/state1.json", {cache:'no-store'})
  const data = await dataRes.json()
  useStore.setState({
    generalStore: data.photoList,
    searchList: data.searchList
  })


  return (
    <html lang="en">
    <body>
    <div className="wrapper">
      <StoreInitializer photoList={data.photoList} searchList={data.searchList} />
      <Header  />
      <main>{children}</main>
      <Footer />
    </div>
    </body>
    </html>
  )
}
