import './globals.css'
import { Lato } from 'next/font/google'
import Header from "./Components/Header/Header";
import Footer from "./Components/Footer/Footer";
import {useStore} from "../src/store";
import StoreInitializer from './StoreInitialier/storeInitializer';


const inter = Lato({
  subsets: ['latin'],
  weight: '400',
})

export const metadata = {
  title: 'Pose Finder',
  description: 'Generated by create next app',
}

  export default async function RootLayout({ children }) {
    const axios = require('axios')
  /*  INITIALIZING DATA ON THE SERVER SIDE  */
    async function fetchData() {
      try {
        const response = await axios.get('https://raw.githubusercontent.com/Blnkfc/Pose-Finder/master/data/state1.json');
        return response.data;
      } catch (error) {
        console.error(error);
        throw error;
      }
    }

    async function getData() {
      return await fetchData();
    }
    const data = await getData();



  useStore.setState({
    photoList: data.photoList,
    searchList: data.searchList,
    addPictureState: data.addPictureState
  })

    /*  INITIALIZING DATA ON THE CLIENT SIDE VIA StoreInitializer COMPONENT  */
  return (
    <html lang="en">
    <body>
    <div className="wrapper">
      <StoreInitializer
          photoList={data.photoList}
          searchList={data.searchList}
          addPictureState={data.addPictureState} />
      <Header  />
      <main>{children}</main>
      <Footer />
    </div>
    </body>
    </html>
  )
}
